import assert from 'node:assert/strict';
import fs from 'node:fs';

const read = relative => fs.readFileSync(new URL(relative, import.meta.url), 'utf8');
const readJson = relative => JSON.parse(read(relative));

const manifest = readJson('../data/databases/hungary-nb1-2025-26/manifest.json');
const normalized = readJson(`../${manifest.files.normalizedPlayers}`);
const report = readJson(`../${manifest.files.normalizationReport}`);
const bootstrap = read('../js/bootstrap.js');
const registry = read('../js/database/database-registry.js');
const seasonModel = read('../js/database/season-model.js');
const seasonService = read('../js/database/season-service.js');
const databaseService = read('../js/database/database-service.js');
const standaloneBuilder = read('../scripts/build-standalone.mjs');
const serviceWorker = read('../sw.js');

assert.equal(manifest.schemaVersion, 2);
assert.equal(manifest.version, '3.1.0');
assert.equal(manifest.competitionId, 'hungary-nb1');
assert.equal(manifest.seasonId, '2025-26');
assert.equal(manifest.season, '2025/26');
assert.equal(manifest.seasonMeta.startYear, 2025);
assert.equal(manifest.seasonMeta.endYear, 2026);
assert.equal(manifest.seasonMeta.status, 'current');
assert.equal(manifest.normalization.primaryFile, 'normalizedPlayers');
assert.equal(manifest.normalization.playerModelVersion, 1);
assert.equal(manifest.normalization.reproducible, true);
assert.equal(manifest.normalization.fallback, 'legacy-layered-database');

assert.equal(normalized.schemaVersion, 2);
assert.equal(normalized.databaseId, manifest.id);
assert.equal(normalized.databaseVersion, manifest.version);
assert.equal(normalized.competitionId, manifest.competitionId);
assert.equal(normalized.seasonId, manifest.seasonId);
assert.equal(normalized.season, manifest.season);
assert.deepEqual(normalized.seasonMeta, manifest.seasonMeta);
assert.equal(normalized.playerModel.version, manifest.normalization.playerModelVersion);
assert.equal(normalized.playerModel.validation.errorCount, 0);
assert.equal(normalized.players.length, 440);
assert.equal(new Set(normalized.players.map(player => player.id)).size, 440);
assert.equal(report.schemaVersion, 2);
assert.equal(report.playerCount, 440);
assert.equal(report.registrationRecords, 464);
assert.equal(report.seasonId, manifest.seasonId);
assert.equal(report.validation.errorCount, 0);
assert.equal(report.playersDigest, normalized.migration.playersDigest);
assert.equal(report.sourceDigest, normalized.migration.sourceDigest);

assert.match(registry, /defaultSeasonId/);
assert.match(registry, /getAvailableSeasons/);
assert.match(registry, /getDatabaseBySeason/);
assert.match(registry, /normalizedPlayers/);
assert.match(registry, /normalizationReport/);
assert.match(registry, /playerModelVersion/);
assert.match(seasonModel, /createSeasonCardId/);
assert.match(seasonService, /loadActiveSeason/);
assert.match(seasonService, /attachSeasonContextToSnapshot/);
assert.match(bootstrap, /loadActiveSeason/);
assert.match(bootstrap, /__FOCISKARTYAK_SEASON__/);
assert.doesNotMatch(bootstrap, /fetchJson\(files\.normalizedPlayers\)/);
assert.match(databaseService, /fetchCached\(files\.normalizedPlayers/);
assert.match(databaseService, /source: 'normalized'/);
assert.match(databaseService, /source: 'legacy-fallback'/);
assert.match(databaseService, /Visszaállás a régi forrásrétegekre/);
assert.match(standaloneBuilder, /normalizedPlayerFile/);
assert.match(standaloneBuilder, /buildDataSource = 'normalized'/);
assert.match(standaloneBuilder, /buildDataSource = 'legacy-layered'/);
assert.match(standaloneBuilder, /standaloneDataSource: buildDataSource/);
assert.match(serviceWorker, /season-model\.js/);
assert.match(serviceWorker, /season-service\.js/);
assert.match(serviceWorker, /season-save-service\.js/);
assert.match(serviceWorker, /players\.normalized\.json/);
assert.match(serviceWorker, /normalization-report\.json/);
assert.match(serviceWorker, /const PWA_CACHE = 'fociskartyak-2026-v\d+'/);

console.log('✓ A 2025/26-os normalizált adatbázis szezonazonosítóval elsődleges forrás; a jövőbeli idények külön manifestből betölthetők');
